	DROP TABLE IF EXISTS MOVIE;
	
	CREATE TABLE MOVIE (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		YEAR VARCHAR(4) NOT NULL,
		TITLE VARCHAR(250) NOT NULL,
		WINNER BOOLEAN DEFAULT FALSE
	);
	
	DROP TABLE IF EXISTS STUDIO;
	
	CREATE TABLE STUDIO (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		NAME VARCHAR(250) NOT NULL
	);
	
	DROP TABLE IF EXISTS PRODUCER;
	
	CREATE TABLE PRODUCER (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		NAME VARCHAR(250) NOT NULL
	);
	
	DROP TABLE IF EXISTS PRODUCERTOMOVIE;
	
	CREATE TABLE PRODUCERTOMOVIE (
		MOVIEID BIGINT NOT NULL,
		PRODUCERID BIGINT NOT NULL
	);
	
	ALTER TABLE PRODUCERTOMOVIE
		ADD FOREIGN KEY (MOVIEID)
		REFERENCES MOVIE(ID);
		
	ALTER TABLE PRODUCERTOMOVIE
		ADD FOREIGN KEY (PRODUCERID)
		REFERENCES PRODUCER(ID);
	
	DROP TABLE IF EXISTS STUDIOTOMOVIE;
	
	CREATE TABLE STUDIOTOMOVIE (
		MOVIEID BIGINT NOT NULL,
		STUDIOID BIGINT NOT NULL
	);
	
	ALTER TABLE STUDIOTOMOVIE
		ADD FOREIGN KEY (MOVIEID)
		REFERENCES MOVIE(ID);
		
	ALTER TABLE STUDIOTOMOVIE
		ADD FOREIGN KEY (STUDIOID)
		REFERENCES STUDIO(ID);